Q1. What is Min-Max scaling, and how it is used in data preprocessing? Provide an example to illustrate its application.

solution:
Min-max scaling, also known as normalization, is a data preprocessing technique used to transform the values of numeric data to a specific range, usually between 0 and 1.This scaling is particularly useful when you need to ensure that all features contribute equally to the learning process in machine learning algorithms.


In [3]:
##for example
import pandas as pd
df=pd.DataFrame({'person':['A','B','C','D','E'],'Height':[150,160,170,180,190]})

from sklearn.preprocessing import MinMaxScaler

min_max=MinMaxScaler()
min_max.fit_transform(df[['Height']])


array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.

solution: The Unit Vector technique, also known as Normalization or Vector Scaling, is a feature scaling method that transforms the data into unit vectors. This technique scales each feature such that the Euclidean norm (L2 norm) of the vector equals 1. This is particularly useful when you want to ensure that all features contribute equally to the distance computations, which is important for algorithm like k-NN, SVM, and PCA.

Difference

1. Unit Vector Scaling:
    * Transform data such that the Euclidean norm(L2 norm) of the feature vector is 1.
    * Each data point is scaled individually.
    * usefull for algorithms that compute distances or dot products.

2. Min-Max Scaling:
    * Transform data to fit within a specific range(e.g., 0 to 1 or -1 to 1)
    * Scales data based on the minimum and maximum values of the feature across the dataset.
    * Useful for algorithms that require data within a specific range.

In [25]:
#for example
import seaborn as sns
df=sns.load_dataset('tips')
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [26]:
from sklearn.preprocessing import normalize
pd.DataFrame(normalize(df[['total_bill','tip']]),columns=['total_bill','tip'])

total_bill       tip
0      0.998238  0.059342
1      0.987357  0.158512
2      0.986407  0.164323
3      0.990372  0.138435
4      0.989395  0.145251
..          ...       ...
239    0.979834  0.199815
240    0.997304  0.073385
241    0.996131  0.087881
242    0.995213  0.097734
243    0.987480  0.157744

[244 rows x 2 columns]

Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.

Principal Component Analysis (PCA) is a statistical technique used for dimensionality reduction in data analysis and machine learning. It identifies patterns and correlations in data and expresses them in terms of principal components. These components are linear combinations of the original features and are ordered by the amount of variance they explain in the data.

In [11]:
import pandas as pd

data = {
    'Math': [85, 70, 90, 60, 75],
    'Science': [90, 75, 88, 70, 80],
    'English': [78, 80, 85, 65, 78],
    'History': [92, 85, 95, 80, 88]
}

df = pd.DataFrame(data)
print(df)


   Math  Science  English  History
0    85       90       78       92
1    70       75       80       85
2    90       88       85       95
3    60       70       65       80
4    75       80       78       88


In [12]:
##Step 1- Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df=pd.DataFrame(scaler.fit_transform(df))

In [15]:
##Step 2- Find Covariance Matrix
import numpy as np
covariance_matrix=np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2],df.iloc[:,3]])
print(covariance_matrix)

[[1.25       1.21106216 1.0406298  1.24793244]
 [1.21106216 1.25       0.88958814 1.19925522]
 [1.0406298  0.88958814 1.25       1.05746048]
 [1.24793244 1.19925522 1.05746048 1.25      ]]


In [16]:
##Step 3 - Find EV and EVs
eigen_values,eigen_vector=np.linalg.eig(covariance_matrix)

In [39]:
eigen_values

array([4.58319009e+00, 3.91440281e-01, 1.25010273e-03, 2.41195223e-02])

In [47]:
sorted_index = np.argsort(eigen_values)[::-1]
sorted_eigenvectors = eigen_vector[:, sorted_index]
sorted_eigenvalues = eigen_values[sorted_index]

In [51]:
#Select the top 2 eigen_vectors

pc = sorted_eigenvectors[:, 0:2] ##Trnasformation is done

In [53]:
pc

array([[ 0.51934128,  0.1573041 ],
       [ 0.49848209,  0.50383412],
       [ 0.46006901, -0.84276671],
       [ 0.5197468 ,  0.10559766]])

In [56]:
transformed_df=np.dot(df.iloc[:,0:4],pc)
new_df=pd.DataFrame(transformed_df,columns=['PC1','PC2'])

In [57]:
new_df

PC1       PC2
0  1.507392  0.735973
1 -0.762231 -0.877696
2  2.402684 -0.154817
3 -3.115379  0.453079
4 -0.032466 -0.156540

Q4. What is relationship between PCA and Feature Extraction and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept.

Principal Component Analysis (PCA) and Feature Extraction are closely related in the context of data preprocessing and dimensionality reduction.

Feature Extraction involves transforming the original data into a new set of features that are usually more informative and less redundant. This is often done to improve the performance of machine learning algorithms.

PCA is a popular technique used for feature extraction because it transforms the original features into a new set of uncorrelated features called principal components. These components are ordered such that the first few retain most of the variance present in the original dataset.

Q5. Your are working on a project to build a recommendation system for a food delivery service. The dataset contains features such as price, rating and delivery time, Explain how you would use Min-Max scaling to preprocess the data.

In [13]:
import numpy as np
df1=pd.DataFrame({'Price':np.random.randint(1000,5000,10),'Rating':np.random.randint(1,10,10),'Delivery_time':np.random.randint(0,24,10)})
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
min_max.fit_transform(df1[['Price','Rating','Delivery_time']]) 

array([[1.        , 1.        , 1.        ],
       [0.46524939, 0.        , 0.        ],
       [0.11474516, 1.        , 0.46666667],
       [0.95884437, 0.4       , 0.13333333],
       [0.80921232, 0.6       , 0.26666667],
       [0.98500954, 0.2       , 0.06666667],
       [0.24448078, 0.4       , 0.8       ],
       [0.17279913, 0.2       , 0.4       ],
       [0.        , 0.8       , 0.8       ],
       [0.36713001, 0.6       , 0.73333333]])

Q6. You are working on a project to build a model to  predict the stock prices. The dataset contains many features, such as company financial data and market tends. Explain how you would use PCA to reduce the dimensionality of the dataset.

In [59]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Create a sample dataset
np.random.seed(42) # For reproducibility
data={
    'Revenue': np.random.uniform(100,1000,50),
    'Profit': np.random.uniform(10,100,50),
    'Expenses': np.random.uniform(50,500,50),
    'Market Share':np.random.uniform(1,50,50),
    'Stock Price':np.random.uniform(20,200,50),
    'Employee Count':np.random.randint(50,1000,50),
    'Customer Satisfaction': np.random.uniform(1,10,50)
}

##Create DataFrame
df=pd.DataFrame(data)

#Standardize the data
scaler=StandardScaler()
df = scaler.fit_transform(df)

#Perform PCA
pca = PCA(n_components=2) 
pc=pca.fit_transform(df)

new_df=pd.DataFrame(data=pc,columns=['PC1','PC2'])
print(new_df)




         PC1       PC2
0   1.622064 -2.599418
1  -0.771510 -0.715053
2  -2.055693 -1.826946
3   1.674217  0.183205
4   0.372914 -0.995896
5  -0.600963 -0.936548
6   0.263886  0.422697
7   1.588595  1.079853
8  -1.553541  0.434139
9  -0.294694 -1.052425
10  0.357407  1.353378
11  1.365966  0.847220
12  0.771800  0.439616
13 -1.753819  0.159753
14 -1.444855  0.323594
15 -1.095296 -0.325889
16 -1.197692  1.387225
17  0.466522 -0.889782
18 -1.511520  2.671004
19 -0.248052 -1.171143
20  0.436564  0.723473
21 -1.623755  1.619971
22  0.534179  1.426447
23 -0.519072 -1.441946
24  0.348845 -1.085610
25 -1.066210  0.064252
26  0.950073 -0.825331
27 -1.941320  0.757462
28  2.738711  0.657608
29 -0.903608  1.909154
30  0.332591 -1.497301
31  0.065533 -0.337640
32  1.980139 -0.390379
33  1.320662  0.957730
34 -1.865564  0.436537
35  0.187364 -0.385535
36 -0.353355 -1.589836
37 -1.746057 -0.298367
38  0.169234 -0.424677
39 -2.760276 -0.127267
40 -0.098833  2.900864
41  1.647058 -0.830271
42  0.37866

In [60]:
# Explained variance
explained_variance = pca.explained_variance_ratio_
print("\nExplained Variance Ratio:\n", explained_variance)


Explained Variance Ratio:
 [0.25088179 0.18666339]


Q7. For a dataset containing the following values:[1,5,10,15,20], perform Min-Max scaling to transform the values to a range of -1 to 1.

In [23]:
df2=pd.DataFrame({'f1':[1,5,10,15,20]})
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(-1,1))
scaler.fit_transform(df2[['f1']])


array([[-1.        ],
       [-0.57894737],
       [-0.05263158],
       [ 0.47368421],
       [ 1.        ]])

Q8. For a dataset containing the following features:[height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?



In [61]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Set seed for reproducibility
np.random.seed(42)

# Generate sample data
num_samples = 100
data = {
    'Height': np.random.uniform(150, 200, num_samples),  # Height in cm
    'Weight': np.random.uniform(50, 100, num_samples),   # Weight in kg
    'Age': np.random.randint(18, 80, num_samples),        # Age in years
    'Gender': np.random.randint(0, 2, num_samples),       # Gender (0: Male, 1: Female)
    'Blood Pressure': np.random.uniform(70, 180, num_samples)  # Blood Pressure in mmHg
}

# Create DataFrame
df = pd.DataFrame(data)

#Standardize the data
scaler=StandardScaler()
df = scaler.fit_transform(df)

#Perform PCA
pca = PCA(n_components=2) 
pc=pca.fit_transform(df)

new_df=pd.DataFrame(data=pc,columns=['PC1','PC2'])
print(new_df)




         PC1       PC2
0   0.252524  0.676745
1  -2.197804 -1.217594
2   0.897272  0.587865
3  -1.226227  0.411631
4   2.054044 -1.790537
..       ...       ...
95  0.038077 -0.089681
96  0.501304  0.298877
97  0.899993 -1.943611
98  1.423279 -1.278581
99  1.427504 -1.420649

[100 rows x 2 columns]
